name: Create and publish a Docker image

# Build and publish a docker image.
# Requires at least an org and image name to work correctly.
# Usage:
#
# jobs:
#   build:
#     uses: cloud-cli/workflows/.github/workflows/docker-ghcr-build.yml@main
#     with:
#       name: 'myorg/my-node-app'
#       baseImage: 'myorg/node:version-hash'
#
# Adds the current directory to the base image and publishes it

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true

      baseImage:
        type: string
        required: true

      buildCommand:
        type: string
        required: false

      defaultBranch:
        type: string
        required: false
        default: main

      withSha:
        type: string
        required: false
        default: true

      withTag:
        type: string
        required: false
        default: false

      type:
        type: string
        required: false
        default: ''

      arch:
        type: string
        required: false
        default: linux/arm64

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      TAG: ghcr.io/${{ inputs.name }}:${{ github.sha }}
      LATEST_TAG: ghcr.io/${{ inputs.name }}:latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Dockerfile
        run: |
          if test ! -f "Dockerfile"; then
            echo 'FROM ghcr.io/${{ inputs.baseImage }}' > Dockerfile
            echo 'ADD . /home/app' >> Dockerfile
          fi
          cat Dockerfile

      - name: Build project
        if: ${{ inputs.buildCommand != '' }}
        run: |
          ${{ inputs.buildCommand }}

      - name: Build Node project
        if: ${{ inputs.type == 'node' }}
        run: |
          docker run --rm -v $PWD:/home -u root -w /home --entrypoint /usr/local/bin/npm ghcr.io/cloud-cli/node:latest run ci

      - name: Build Vite project
        if: ${{ inputs.type == 'vite' }}
        run: |
          docker run --rm -v $PWD:/home/app -u root ghcr.io/cloud-cli/vite:latest build

      - name: Build SHA tag
        if: inputs.withSha != 'false'
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ inputs.arch }}
          push: true
          tags: ${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build latest tag
        if: github.ref_name == ${{ inputs.defaultBranch }} && inputs.withTag != 'false'
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ inputs.arch }}
          push: true
          tags: ${{ env.LATEST_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
