name: Create and publish a Docker image

# Build and publish a docker image.
# Requires at least an org and image name to work correctly.
# Usage:
#
# jobs:
#   build:
#     uses: cloud-cli/workflows/.github/workflows/docker-ghcr-build.yml@main
#     with:
#       image: 'my-node-app'
#       baseName: 'node'

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      baseImage:
        type: string
        required: true
      defaultBranch:
        required: false
        type: string
        default: main

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-18.04
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      TAG: ${{ env.REGISTRY }}/${{ inputs.image }}:${{ github.sha }}
      LATEST_TAG: ${{ env.REGISTRY }}/${{ inputs.image }}:latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Dockerfile
        run: |
          echo 'FROM ${{ env.REGISTRY }}/${{ inputs.baseImage }} \nADD . /home/app'

      - name: Build branch
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build latest
        if: github.ref == 'refs/heads/${{ inputs.defaultBranch }}'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.LATEST_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
