name: Create and publish a Docker image

# Build and publish a docker image.
# Requires at least an org and image name to work correctly.
# Usage:
#
# jobs:
#   build:
#     uses: cloud-cli/workflows/.github/workflows/docker-ghcr-build.yml@main
#     with:
#       image: 'my-node-app'
#       baseImage: 'node'
#
# Adds the current directory to the base image and publishes it

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      baseImage:
        type: string
        required: true

      buildCommand:
        type: string
        required: false

      defaultBranch:
        required: false
        type: string
        default: main

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-18.04
    permissions:
      contents: read
      packages: write

    env:
      TAG: ghcr.io/${{ inputs.image }}:${{ github.sha }}
      LATEST_TAG: ghcr.io/${{ inputs.image }}:latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Dockerfile
        run: |
          echo 'FROM ghcr.io/cloud-cli/${{ inputs.baseImage }} \nADD . /home/app'

      - name: Build project
        if: ${{ inputs.buildCommand != '' }}
        run: |
          sh ${{ inputs.buildCommand }}

      - name: Build branch
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.TAG }}
